name: Test Project
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Debug
        run: ls -la
      - name: Debug second-action
        run: ls -la second-action-react-demo/
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix second-action-react-demo
      - name: Run tests
        run: npm test --prefix second-action-react-demo
